### ISSUE TITLE
6. Show connected wallet info 

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch8.buidlguidl.com#5]
## Goal

When a user connects to the dApp, let's display 2 things:

1. Is the connected address a member of the batch? (is the in the allowList)
2. Is the connected address already checked in?

Feel free to place that info whenever you want. It could be just some icons that show next to the wallet for members.

For more info about the contract: #10

**Comment by umutarray** [comment]
Hi, i would like to do that. Can you assign it to me?

**Comment by ruhneb2004** [comment]
If this is not already taken, I would like to work on this issue

Given below is a design of how  I would like to implement this feature. There will be a batch member logo for the members (bottom left) , and the checkedIn and check In icons will be shown based on the completion of the challenge. The checkn In on clicking will open the github #10 page.

<img width="915" alt="Screenshot 2024-08-19 at 8 15 50 PM" src="https://github.com/user-attachments/assets/252f0a45-2b95-4f0a-92ec-d138b4ffeac3">
