### ISSUE TITLE
5. Get the check-in count from the BatchRegistry contract 

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch8.buidlguidl.com#6]
## Goal

There is a "To Be implemented" string in `packages/nextjs/app/page.tsx` that should show the number of builders that have checked in to the contract.

We want to show the real count (reading from the BatchRegistry contract)

For more info about the contract: https://github.com/BuidlGuidl/batch8.buidlguidl.com/issues/10

**Comment by RafaelCaso** [comment]
working on this

**Comment by RafaelCaso** [comment]
My proposed solution for this issue. Would love to get other batch member's input!
<img width="1203" alt="Screen Shot 2024-08-12 at 5 06 35 PM" src="https://github.com/user-attachments/assets/813db24b-1733-4c47-8b90-b6d83ba88348">

**Comment by RafaelCaso** [comment]
This should take advantage of the isLoading state returned by useScaffoldReadContract. That would eliminate the need for the isNan() check

**Comment by indralukmana** [comment]
@RafaelCaso maybe we can do it like this?

```javascript
const result = isLoading ? "..." : Number(checkedIn);
```

I'm still not sure if `checkedIn` would always result in `number` or can be `NaN` if the loading is done (true). One pitfall I'm thinking if we are using `...` for conflating the result of loading and `NaN` checking of `checkedIn` value we would miss a possible error when the loading is done and the `checkedIn` is `NaN`. Maybe it is fine to just show `NaN` or maybe add some checking and change the `result` (making it a `let`) when the `checkedIn` is actually a `NaN`.

with the above we can simplify the codes for showing the `span` in the screenshot from line 13 to 17 into

```javascript
<span className="font-bold">Checked in builders count: {result}</span>
```

**Comment by RafaelCaso** [comment]
@indralukmana 

yeah, replacing Number.isNaN(result) with isLoading makes more sense to me.

if checkedIn fails it would be because of an error from the block chain, no? So maybe we would add a catch block and return a simple "Something wen't wrong, please try again" kind of message?

**Comment by indralukmana** [comment]
@RafaelCaso 
I'm honestly not sure what kind of error would result there, haven't dig in into the inner details of ScaffoldETH hooks yet maybe from blockchain or provider/rpc or something else entirely.

Maybe you can write and do PR then ask your questions in the PR and people who are more knowledgeable can give more insights. It is kind of hard not having real codes to check and do stuff 😁

**Comment by derrekcoleman** [comment]
@RafaelCaso and @indralukmana, I definitely appreciate the conversation about error handling! We want users to have a good experience, even when things go wrong.

> if checkedIn fails it would be because of an error from the block chain, no?

[useScaffoldReadContract](https://docs.scaffoldeth.io/hooks/useScaffoldReadContract) is a wrapper around wagmi's [useReadContract](https://wagmi.sh/react/api/hooks/useReadContract), which has return fields related to possible [errors](https://wagmi.sh/react/api/hooks/useReadContract#error) and [failureReasons](https://wagmi.sh/react/api/hooks/useReadContract#failurereason). These are definitely worth learning as a FE developer reading blockchain data!

> So maybe we would add a catch block and return a simple "Something wen't wrong, please try again" kind of message?

Back to our implementation, giving the user information like this is a great idea. Displaying more info about the error on the page or in a [toast](https://daisyui.com/components/toast/) is a common pattern for good reason.

Start simple by handling all errors in the same way, then add complexity for (displaying) different error reasons one at a time.

**Comment by RafaelCaso** [comment]
PR is in
