### ISSUE TITLE
3. Change the Logo / title / subtitle

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch8.buidlguidl.com#8]
## Goal

Update your batch's mainpage. 

![284656861-52a77020-0c08-4136-8cc5-244bc3bd088a](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/2486142/f9d3495a-9946-4b8e-ac55-8e00cdc380e0)

- Create a random logo (or use Dall-E!) to generate a batch logo
- title: Batch #{batch_number}
- subtitle: Whatever you feel appropriate :)

**Comment by 0xzeze** [comment]
I just created a logo with AI . Do you like it guys? 
<img width="702" alt="Ekran Resmi 2024-08-09 19 57 39" src="https://github.com/user-attachments/assets/c3a3aab1-2843-494a-ac7e-85bbd8b361aa">

**Comment by rohan-ahire06** [comment]
It looks good👍🏻

**Comment by indralukmana** [comment]
Looks good I think, maybe you should create a PR for it @0xzeze and let the maintainer know

**Comment by phipsae** [comment]
Very nice logo! @0xzeze go ahead and create a PR, so that it can be merged
